### ISSUE TITLE
爬虫源全关闭，novel_crawl在执行什么操作呢

### ISSUE THREAD

**Issue by HelloNick666** [201206030/novel-plus#36]
1.启动novel_crawl
2.进入爬虫管理系统
3.将爬虫源列表中的所有源全部关闭，这个时候novel_crawl在执行什么联网操作呢？

我的服务器经常oom，爬虫源列表全部关闭后，不会出现oom.
我想能不能将现有的小说各个章节都尽快爬全，应该怎么配置呢？

**Comment by 201206030** [comment]
爬虫程序启动起来后，后台线程就自动更新章节，要快的话，可以放到本地机器上运行（相较于小内存服务器），也可以多放几台机器上，让别人帮忙



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [201206030/novel-plus] 爬虫源全关闭，novel_crawl在执行什么操作呢 (#36)




 
1.启动novel_crawl
 2.进入爬虫管理系统
 3.将爬虫源列表中的所有源全部关闭，这个时候novel_crawl在执行什么联网操作呢？
 
我的服务器经常oom，爬虫源列表全部关闭后，不会出现oom.
 我想能不能将现有的小说各个章节都尽快爬全，应该怎么配置呢？

**Comment by HelloNick666** [comment]
好的  非常感谢您的回答。
我在管理平台中的把几个爬虫源全部关闭，程序就不会崩溃，但是我看日志，好像程序也还在爬取数据。
我是否可以这样理解，把爬虫源关闭后，不会从这些源获取新的小说。 但是自动更新程序还是在更新已有的小说章节？

**Comment by 201206030** [comment]
对的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 下午5:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [201206030/novel-plus] 爬虫源全关闭，novel_crawl在执行什么操作呢 (#36)




 
好的  非常感谢您的回答。
 我在管理平台中的把几个爬虫源全部关闭，程序就不会崩溃，但是我看日志，好像程序也还在爬取数据。
 我是否可以这样理解，把爬虫源关闭后，不会从这些源获取新的小说。 但是自动更新程序还是在更新已有的小说章节？
