### ISSUE TITLE
docker搭建，导入数据库之后显示乱码

### ISSUE THREAD

**Issue by mxxisbest** [201206030/novel-plus#8]
截图如下：

![image](https://vip1.loli.net/2020/05/14/ts1PIahViwKE3Fc.png)

**Comment by 201206030** [comment]
数据库的编码不对，导入前应该设置 set names utf8

**Comment by mxxisbest** [comment]
设置了之后又导入了一遍，还是乱码。

**Comment by mxxisbest** [comment]
> 设置了之后又导入了一遍，还是乱码。

首页乱码，点进去之后不乱码了。

**Comment by 201206030** [comment]
首页有缓存

**Comment by mxxisbest** [comment]
> 首页有缓存

非常感谢！
